spring:
  cloud:
    stream:
      bindings:
        demo-queue:
          #The presence of "group" tells the binder to follow the "consumer group" pattern
          group: SINK
      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: admin
                clientPassword: admin
      solace:
        bindings:
          demo-queue:
            consumer:
              #This adds a topic subscription w/ wildcards to the queue created with a name of TEMPS.Q.SINK above 
              queueAdditionalSubscriptions: sensor/temperature/>
                
logging:
  level:
    root: DEBUG
    com.solacesystems.jcsmp: DEBUG
    org.springframework: DEBUG
    
server:
  port: 8099